### ISSUE TITLE
Meeting 24/07/24 Note this time 17:00 BST!

### ISSUE THREAD

**Issue by THS-on** [keylime/meetings#78]
## Attendees

- [x] @ansasaki 
- [ ] @aplanas 
- [x] @deeglaze
- [x] @edwards-n 
- [x] @galmasi 
- [x] @Isaac-Matthews
- [ ] @kkaarreell
- [ ] @lkatalin  
- [ ] @lukehinds 
- [x] @maugustosilva
- [ ] @mayaCostantini
- [x] Marcos Tork
- [ ] @mdrocco
- [ ] @mbestavros 
- [x] @mheese
- [ ] @mruffin
- [x] @mpeters 
- [ ] Niteesh Dubey
- [ ] @osresearch 
- [ ] @ruocco
- [x] @stringlytyped
- [ ] @stefanberger
- [x] @THS-on
- [x] @tpletcher-hpe 
- [x] @tylerfanelli
- [ ] @ueno
- [ ] @sergio-correia 
- [x] Supreshna
- [x] Shiva Dasari
- [ ] Christian Schilling

Time: 24/07/24 17:00 BST (https://www.timeanddate.com/worldclock/fixedtime.html?msg=Keylime+Meeting&iso=20231025T1700&p1=136&ah=1)

Meeting link: https://uni-kiel.zoom-x.de/j/62369420015?pwd=faCUFRXmWSGwJcQUobsREl9vIU8fvM.1

## Agenda

* Workstreams
     * Updates on the next steps for https://github.com/keylime/keylime/pull/1523
        * Measured Boot data models are getting converted
        * Registrar will likely include the trust store first
        * Current verifier will be converted to new framework
     * Updates on the work on the attestation operator
        * Development currently halted -> depends also on push model implementation 
     * TEE presentation by Tyler
       * Detailed notes can be found here https://github.com/keylime/enhancements/pull/108#issuecomment-2249744703 
     * Consideration of CoRIM for reference values 
       * deferred to next meeting
     * Fedora container issue
       *  Copy a known good image to our name space
       * Update on release
     
* Open PRs
     * https://github.com/keylime/keylime/pull/1568
       * Mostly good only small changes requested
     * https://github.com/keylime/keylime/pull/1545
       * deferred to next meeting

**Comment by mheese** [comment]
I'm interested to get some updates on the work for the attestation operator. Last to my knowledge Red Hat wanted to continue the work here. I am particularly curious about the policy design. However, all I can see is work to make the deployment possible through a CRD (true operator essentially).
