### ISSUE TITLE
Meeting 28/08/24 Note again at 17:00 BST!

### ISSUE THREAD

**Issue by THS-on** [keylime/meetings#79]
## Attendees

- [x] @ansasaki 
- [ ] @aplanas 
- [ ] @deeglaze
- [ ] @edwards-n 
- [ ] @galmasi 
- [ ] @Isaac-Matthews
- [ ] @kkaarreell
- [ ] @lkatalin  
- [ ] @lukehinds 
- [ ] @maugustosilva
- [ ] @mayaCostantini
- [x] Marcos Tork
- [ ] @mdrocco
- [ ] @mbestavros 
- [x] @mheese
- [ ] @mruffin
- [ ] @mpeters 
- [ ] Niteesh Dubey
- [ ] @osresearch 
- [ ] @ruocco
- [ ] @stringlytyped
- [ ] @stefanberger
- [x] @THS-on
- [ ] @tpletcher-hpe 
- [x] @tylerfanelli
- [ ] @ueno
- [x] @sergio-correia 
- [x] Supreshna
- [ ] Shiva Dasari
- [ ] Christian Schilling

Time: 28/08/24 17:00 BST (https://www.timeanddate.com/worldclock/fixedtime.html?msg=Keylime+Meeting&iso=20240828T1700&p1=136&ah=1)
Link: https://uni-kiel.zoom-x.de/j/66056379871?pwd=Xky25RkxLbcAajLDGb615bfB8k8HwI.1
Meeting ID: 660 5637 9871
Passcode: 317939

## Topics
* Changing meeting time
  * Vote can be found here: https://terminplaner.dfn.de/ujTyqpKJ2Gr5e7nf 
* Update on https://github.com/keylime/enhancements/pull/108
  * Was updated including the new ideas. Please comment on it 
* Keylime policy bugs
  * @ansasaki is working on it 
* https://github.com/keylime/keylime/pull/1545
  * Discussion to next meeting 
* CORIM and Keylime
  * Currently no standards really used by Keylime for refrence values and policies
  * What use cases do we have?
    * Needs further discussion 
  * Folks working on CORIM and RATS will give a presentation at the next monthly meeting
* https://github.com/keylime/keylime/issues/1612
   * Agreed to switch this to a warning, as no trust decision from Keylime depends on enforcing that field

**Comment by Isaac-Matthews** [comment]
Can we discuss this if we have the time:
